version: '3.9'

services:
  catalogdb: 
    image: mongo

  basketdb: 
    image: redis:alpine

  discountdb:
    image: postgres



  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: ./src/services/catalog/Catalog.API/
      dockerfile: Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: ./src/services/basket/Basket.API/
      dockerfile: Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: ./src/Services/Discount/Discount.API/
      dockerfile: Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:


